# =========================
# Pharmora Netlify Config
# Static Multi Page App
# =========================


[build]

command="npm run build"

publish="."





# =========================
# SPA ROUTING
# =========================

[[redirects]]

from = "/*"

to = "/index.html"

status = 200








# =========================
# SECURITY HEADERS
# =========================


[[headers]]

for = "/*"


[headers.values]


X-Frame-Options = "DENY"


X-Content-Type-Options = "nosniff"


Referrer-Policy = "strict-origin-when-cross-origin"


Permissions-Policy = "camera=(), microphone=(), geolocation=()"









# =========================
# HTML
# Always Fresh
# =========================


[[headers]]

for = "/*.html"


[headers.values]


Cache-Control = """
no-cache,
no-store,
must-revalidate
"""










# =========================
# CONFIG + DATA
# Dynamic Content
# =========================


[[headers]]

for = "/config/*"


[headers.values]


Cache-Control = "no-cache"







[[headers]]

for = "/data/*"


[headers.values]


Cache-Control = "no-cache"










# =========================
# CSS CACHE
# =========================


[[headers]]

for = "/css/*"


[headers.values]


Cache-Control = """
public,
max-age=604800
"""










# =========================
# JAVASCRIPT CACHE
# =========================


[[headers]]

for = "/js/*"


[headers.values]


Cache-Control = """
public,
max-age=604800
"""







[[headers]]

for = "/components/*"


[headers.values]


Cache-Control = """
public,
max-age=604800
"""










# =========================
# IMAGES / ASSETS
# =========================


[[headers]]

for = "/assets/*"


[headers.values]


Cache-Control = """
public,
max-age=31536000,
immutable
"""